export const standardSchema = {
	companyName: {
		application_info: {},
		base_type: 'string',
		description: 'CompanyNamename.',
		max_length: null,
		min_length: 1,
		name: 'companyName',
		order: 732,
		readonly: false,
		required: true,
		title: 'Companyname',
		type: 'string',
	},
	description: {
		application_info: {},
		base_type: 'string',
		description: 'Positiondescription',
		max_length: null,
		min_length: 0,
		name: 'description',
		order: 736,
		readonly: false,
		required: false,
		title: 'Positiondescription',
		type: 'string',
	},
	endYear: {
		application_info: {},
		base_type: 'int',
		description: 'Endyear',
		max: null,
		min: null,
		name: 'endYear',
		order: 735,
		readonly: false,
		required: false,
		title: 'Endyear',
		type: 'int',
	},
	startYear: {
		application_info: {},
		base_type: 'int',
		description: 'Startyear',
		max: null,
		min: null,
		name: 'startYear',
		order: 734,
		readonly: false,
		required: false,
		title: 'Startyear',
		type: 'int',
	},
	title: {
		application_info: {},
		base_type: 'string',
		description: 'Title',
		max_length: null,
		min_length: 0,
		name: 'title',
		order: 733,
		readonly: false,
		required: false,
		title: 'Title',
		type: 'string',
	},
};
